services:
  app:
    container_name: cer-nlp
    image: cer-nlp
    build:
      context: .
      dockerfile: python.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ".:/cer-nlp"
    environment:
      - DJANGO_SETTINGS_MODULE=BertAPI.settings
    tty: true
    restart: unless-stopped
