# Generated by Django 4.1.6 on 2023-03-10 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
