# Generated by Django 4.1.6 on 2023-03-10 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
