# Generated by Django 4.1.6 on 2023-03-13 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
