# Generated by Django 4.1.6 on 2023-03-13 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_user_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
