# Generated by Django 4.1.6 on 2023-03-14 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserUsage',
        ),
    ]
