# Generated by Django 4.1.6 on 2023-03-15 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0018_remove_customuser_last_login_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
